// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnicvdcjbweavqdffnxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduaWN2ZGNqYndlYXZxZGZmbnhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTY0MTksImV4cCI6MjA1ODM5MjQxOX0.GasD2dSUYhqVTtD1T52tbfAeFScrkh5eJWa-E-Z8BZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);